default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cocktail_dev

test:
  <<: *default
  database: cocktail_test

production:
  <<: *default
  database: cocktail
